### ISSUE TITLE
recognizing more colors

### ISSUE THREAD

**Issue by ahillio** [wader/ansisvg#2]
If I use color codes like `\e[0;32m` in my shell scripts I see the color in the svg.

But the colors from [lolcat](https://github.com/busyloop/lolcat) show up as grey in the svg `ansisvg` creates.

I have no idea how `lolcat` gets those colors.  Have you seen that program?  It would be so amazing to be able to pipe lolcat to ansisvg - SO amazing.

**Comment by ahillio** [comment]
screenshot of `lolcat`'s colorzation
![](https://github.com/busyloop/lolcat/raw/master/ass/screenshot.png)

**Comment by ahillio** [comment]
Wait... `lolcat --help | ansisvg > file.svg` works just fine... but my script invoking lolcat resulted in a file that was just grey...

**Comment by wader** [comment]
Hey, could it be that lolcat somehow detects if it should use color output or not? there is a `-f` to force color even if stdout is not a tty (like when piping to some other program).

**Comment by wader** [comment]
Weirdly it seems like `--help` forces color by default, confusing. So try `... | lolcat -f | ansisvg`

**Comment by ahillio** [comment]
Wow!  Yes `lolcat -f` is needed to pipe to `ansisvg`.  Thank you!

**Comment by ahillio** [comment]
This is a really awesome project.  Was generating svg's in this manner impossible before you created a program to do it?

**Comment by wader** [comment]
No i was not the first one :) There are some similar projects but they either were hard to use, produced not so good looking output or are more focused on recording to an animated svg.

**Comment by wader** [comment]
Have a look at https://github.com/marionebl/svg-term-cli or https://github.com/F1LT3R/ansi-to-svg etc

**Comment by ahillio** [comment]
Well thanks a bunch!  For creating the software, and helping me resolve this issue with the different program.  `ansisvg` works great :)

**Comment by wader** [comment]
No problem, glad you like it!
