### ISSUE TITLE
Allow loading of external fonts

### ISSUE THREAD

**Issue by patrislav1** [wader/ansisvg#4]
I currently patch `ansisvg`'s output to fix the rendering of Powerline symbols:

```
ansisvg -fontname "Ubuntu Mono" -fontsize 16 | sed 's?<style>?<style>@import url("https://cdn.jsdelivr.net/gh/wernight/powerline-web-fonts/PowerlineFonts.css");?g'
```

(I'm a dilettante at web tech, so not sure if this is the right way - but it works)

Wondering if it makes sense to add some kind of option for external fonts (or external CSS in general) to avoid having to patch the generated files.

**Comment by wader** [comment]
Hey, yeah that would be nice. Any idea how it could be done? some generic argument to prepend text or something more font specific? thinking it would be nice to make it easy to embed a font to not make the svg depend on external resources?

**Comment by wader** [comment]
Hmm tricky, looking at https://cdn.jsdelivr.net/gh/wernight/powerline-web-fonts/PowerlineFonts.css it does not look trivial to embed as it depend on other resources (in differens paths) and i think you would have to use data: urls to embed? but i could be wrong

Maybe it should be two differente argument, one to add a font file via filsystem path and one to inject extra css?

**Comment by patrislav1** [comment]
Yes, sounds good.
