### ISSUE TITLE
Animatable screen using CSS animations

### ISSUE THREAD

**Issue by wader** [wader/ansisvg#42]
It struck me that maybe one can use CSS animations to created a animated screen? but to do it probably some more things needs to be in place:
- How to capture control codes? Run subprocess with a pty?
  - Interactive or script ala https://github.com/charmbracelet/vhs?
- Much more complete ANSI decoder, cursor movements, draw instructions etc
- Render to a screen buffer somehow at certain FPS or when things change?
- Render SVG using CSS to animate

**Comment by wader** [comment]
But on the other hand it quite nice that the source is kind of small and easy to overlook atm, maybe has enough features :)

**Comment by patrislav1** [comment]
If I had a use case like that I’d probably just use asciinema and a companion tool, such as https://github.com/marionebl/svg-term-cli

**Comment by wader** [comment]
Doh! true and now i remember i probably played around with some of those tools before doing ansisvg :) let's keep ansisvg focused on "screenshotting" for now :)
