### ISSUE TITLE
Just a head's up

### ISSUE THREAD

**Issue by im-sampm** [wader/ansisvg#46]
This is a brilliant piece of software!

I was going to submit this issue to ask for a few features such as padding and adding a window frame.

However, I just came across this tool which is very similar and has those features: https://crates.io/crates/term-transcript-cli

Life is short, figured I'd give you a head's up!

**Comment by wader** [comment]
> This is a brilliant piece of software!

Hey! thanks

> I was going to submit this issue to ask for a few features such as padding and adding a window frame.

@patrislav1 started looking into margin/border support here https://github.com/wader/ansisvg/pull/43

> However, I just came across this tool which is very similar and has those features: https://crates.io/crates/term-transcript-cli
> 
> Life is short, figured I'd give you a head's up!

No worries, i think there is room for all of them :) we should probably add a "similar tools" section also.

Had a quick loo. Interestingly similar approach to rendering via template and usage of `switch` (for fallback) and `animate` (animate the viewbox) elements.

**Comment by wader** [comment]
Closing. I guess the feature request about border is covered by the PR i linked
