### ISSUE TITLE
Use viewBox instead of width and height

### ISSUE THREAD

**Issue by patrislav1** [wader/ansisvg#49]
Current version generates files incompatible with asciidoctor-pdf:
https://docs.asciidoctor.org/pdf-converter/latest/image-paths-and-formats/#image-formats

Not sure if we can use `viewBox` and get rid of `width`/`height` completely, or if it needs to be a commandline option. `viewBox` also probably works in `px` only and not in `em`/`ch`?

**Comment by wader** [comment]
Nice finding, sounds like a good idea to try. Ideally no command line option if possible i think? you think it might also fix #48?
